version: '3.4'

services:

  db_mysql:

    image: mysql:5.7

    container_name: db_mysql

    volumes:
      - db_mysql_data:/var/lib/mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: r00tp@$$WoRd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user_wordpress
      MYSQL_PASSWORD: pwd_W0rdPr3$$

  wordpress:

    depends_on:
      - db_mysql

    image: wordpress:latest

    container_name: frontend

    volumes:
      - wordpress_files:/var/www/html

    ports:
      - "8000:80"

    restart: always

    environment:
      WORDPRESS_DB_HOST: db_mysql:3306
      WORDPRESS_DB_USER: user_wordpress
      WORDPRESS_DB_PASSWORD: pwd_W0rdPr3$$

volumes:
  db_mysql_data:
  wordpress_files: